language: php

sudo: false

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

env:
  - LARAVEL=5.7
  - LARAVEL=5.6
  - LARAVEL=5.5
  - LARAVEL=5.4
  - LARAVEL=5.3
  - LARAVEL=5.2
  - LARAVEL=5.1
  - LARAVEL=5.0

matrix:
  exclude:
    - env: LARAVEL=5.7
      php: 7.0
    - env: LARAVEL=5.7
      php: 5.6
    - env: LARAVEL=5.6
      php: 7.0
    - env: LARAVEL=5.6
      php: 5.6
    - env: LARAVEL=5.5
      php: 5.6

before_script:
  - composer require "illuminate/database ${LARAVEL}.*"
  - composer update --no-interaction

script:
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/php-coveralls --verbose
